### PR TITLE
final touches on the doc

### PR DESCRIPTION
**Pull request by telephon**
should we also use the symbol variant in the help file or is it better to keep the escaping """s?

### CODE REVIEW

**Comment by telephon** [comment]
Added it here: https://github.com/supercollider-quarks/quarks/blob/master/directory.txt

**Comment by telephon** [comment]
Do you want to announce it? https://scsynth.org/

**Comment by capital-G** [comment]
> Added it here: https://github.com/supercollider-quarks/quarks/blob/master/directory.txt

without a PR https://github.com/supercollider-quarks/quarks/pull/132 ? :O


> Do you want to announce it? https://scsynth.org/

Sounds like a good idea - do you want to write something or should I do it?

**Comment by telephon** [comment]
> Sounds like a good idea - do you want to write something or should I do it?
Please go ahead, if you like!

**Pull request merged**
